pops<-read.csv("mice_pheno.csv") # read the file and store in 'pops'vector, this is the whole
#population which is usually not the case in real experiments
head(pops)# see the first few lines
hf <- pops [pops$Diet == "hf" & pops$Sex == "F", 3] # vector hf made from 'pops' and 
#extract from the Diet column only 'hf' but all columns & select from 'sex' column only females
# and display values of the third column which is Bodyweight.
chow <- pops [pops$Diet == "chow" & pops$Sex == "F", 3]# repeat the same for chow
mean(hf) - mean(chow)# this is the mean between hf and chow Bodyweights for females
x <- sample(hf, 12) # another vector x from hf which randomly samples 12 bodyweights (females)
y<- sample(chow, 12)#same for chow and vector y
mean (x) - mean(y)# mean for this random values which will change each time it is run
#as it is a random variable
#now to test the CLT theorem
Ns <- c(3, 5, 10, 25)# create Ns of 4 values
B <- 10000# B vector stands for 10000
res <- sapply (Ns, function(n){#create res vector to sapply Ns of 4 values as specified as function n
  sapply(1:B, function(j){#which will be sapply-'ied' 1:B (10000) times as function j
    mean(sample(hf, n)) - mean(sample(chow, n))#finally the real deal is the mean of hf - chow
  })# but each (hf and chow means) are randomly taken (sample command) n times as defined by Ns (code line 14,16)
})#http://www.dummies.com/how-to/content/how-to-create-a-function-in-r.html
#http://www.ats.ucla.edu/stat/r/library/intro_function.htm
par(mfrow=c(2,2))# we don't have rafalib as it is custom made this command is to display
#figures generated by the following commands in 2 row x 2 column format.
for (i in seq(along=Ns)){#http://www.dummies.com/how-to/content/how-to-loop-through-values-in-r.html
  title<- paste("Avg=", signif(mean(res[,i]), 3))
  title<- paste(title,"SD=", signif(sd(res[,i]), 3))
  qqnorm(res[,i], main=title)
  qqline(res[,i])
}
